### ISSUE TITLE
Mismatch in url

### ISSUE THREAD

**Issue by joshicola** [liezl200/Molly#3]
Assets/Generator.cs has a different URL than the backend files:

54                 string url = "http://fcb60fc2.ngrok.io/";

while backend/voice_to_text/app.py has:

57     app.run(host="0.0.0.0", port=5555)

and backend/nlp_and_search/app.py has:

116     app.run(host=socket.gethostbyname(socket.gethostname()))

Having these consistent on a local machine would enable experimenters to move this project forward with a little more ease.

Great project!
I have already learned a lot!

**Comment by liezl200** [comment]
This was an unfortunate product of the rushed spirit of how we coded this solution, and our intentions not to deploy and release this app. 

This url is a hardcoded url that allows us to demo the product without deploying (https://ngrok.com/). So what you will want to do is run the backend server on a machine's localhost, then use ngrok to tunnel to that machine's localhost. Then replace that URL on line 54 with the correct proxy URL from ngrok. Let me know if you have any more issues with this.

EDIT: One thing to note is that it isn't necessary to use ngrok to remote tunnel to your localhost. You are free to use whatever you wish to set up a proxy URL that corresponds to the localhost server where the backend is running.
